services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:8.2-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data:
