# Use slim Python image for speed + small size
FROM python:3.12-slim

# Set workdir inside the container
WORKDIR /app

# Install dependencies first (cache efficient)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the source code
COPY . .

# Run Flask app
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
